[tools]
bun = "latest"
go = "latest"
node = "latest"
tree-sitter = "latest"

[tasks]
build = ["cd tree-sitter-qc && tree-sitter generate", "go build"]

[tasks.ts-build]
run = ["tree-sitter generate", "tree-sitter parse"]
dir = "{{ config_root }}/tree-sitter-qc"

[tasks.ts-version]
run = ["tree-sitter version"]
dir = "{{ config_root }}/tree-sitter-qc"
