id = "qc"
name = "QC"
version = "0.1.0"
schema_version = 1
authors = ["noClaps <contact@zerolimits.dev>"]
description = "QC extension for Zed"
repository = "https://github.com/noClaps/qcsim"

[grammars.qc]
repository = "https://github.com/noClaps/qcsim"
path = "tree-sitter-qc"
rev = "a55f5307da7748490e17a94b33491f9dfe65e848"
