/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 102
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 68
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  sym_var_name = 2,
  anon_sym_COMMA = 3,
  sym_number = 4,
  sym_uint = 5,
  anon_sym_PIPE0_GT = 6,
  anon_sym_PIPE1_GT = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  anon_sym_PLUS = 10,
  anon_sym_DASH = 11,
  anon_sym_STAR = 12,
  anon_sym_SLASH = 13,
  anon_sym_CARET = 14,
  anon_sym_sin_LPAREN = 15,
  anon_sym_cos_LPAREN = 16,
  anon_sym_tan_LPAREN = 17,
  anon_sym_root_LPAREN = 18,
  sym_pi = 19,
  sym_imag = 20,
  sym_euler = 21,
  anon_sym_measure_LPAREN = 22,
  anon_sym_x_LPAREN = 23,
  anon_sym_y_LPAREN = 24,
  anon_sym_z_LPAREN = 25,
  anon_sym_hadamard_LPAREN = 26,
  anon_sym_phase_LPAREN = 27,
  anon_sym_pi_8_LPAREN = 28,
  anon_sym_cnot_LPAREN = 29,
  anon_sym_cz_LPAREN = 30,
  anon_sym_swap_LPAREN = 31,
  anon_sym_toffoli_LPAREN = 32,
  anon_sym_SLASH_SLASH = 33,
  aux_sym__comment_token1 = 34,
  sym_source_file = 35,
  sym_variable_declaration = 36,
  sym_var_expr = 37,
  sym_qubit_zero = 38,
  sym_qubit_one = 39,
  sym__expr = 40,
  sym__binary_expr = 41,
  sym_add = 42,
  sym_sub = 43,
  sym_mul = 44,
  sym_div = 45,
  sym_exp = 46,
  sym__var_fn = 47,
  sym_sin = 48,
  sym_cos = 49,
  sym_tan = 50,
  sym_root = 51,
  sym__constant = 52,
  sym__qc_fn = 53,
  sym_measure = 54,
  sym_pauli_x = 55,
  sym_pauli_y = 56,
  sym_pauli_z = 57,
  sym_hadamard = 58,
  sym_phase = 59,
  sym_pi_by_8 = 60,
  sym_controlled_not = 61,
  sym_controlled_z = 62,
  sym_swap = 63,
  sym_toffoli = 64,
  sym__comment = 65,
  aux_sym_source_file_repeat1 = 66,
  aux_sym_source_file_repeat2 = 67,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [sym_var_name] = "var_name",
  [anon_sym_COMMA] = ",",
  [sym_number] = "number",
  [sym_uint] = "uint",
  [anon_sym_PIPE0_GT] = "|0>",
  [anon_sym_PIPE1_GT] = "|1>",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_CARET] = "^",
  [anon_sym_sin_LPAREN] = "sin(",
  [anon_sym_cos_LPAREN] = "cos(",
  [anon_sym_tan_LPAREN] = "tan(",
  [anon_sym_root_LPAREN] = "root(",
  [sym_pi] = "pi",
  [sym_imag] = "imag",
  [sym_euler] = "euler",
  [anon_sym_measure_LPAREN] = "measure(",
  [anon_sym_x_LPAREN] = "x(",
  [anon_sym_y_LPAREN] = "y(",
  [anon_sym_z_LPAREN] = "z(",
  [anon_sym_hadamard_LPAREN] = "hadamard(",
  [anon_sym_phase_LPAREN] = "phase(",
  [anon_sym_pi_8_LPAREN] = "pi_8(",
  [anon_sym_cnot_LPAREN] = "cnot(",
  [anon_sym_cz_LPAREN] = "cz(",
  [anon_sym_swap_LPAREN] = "swap(",
  [anon_sym_toffoli_LPAREN] = "toffoli(",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym__comment_token1] = "_comment_token1",
  [sym_source_file] = "source_file",
  [sym_variable_declaration] = "variable_declaration",
  [sym_var_expr] = "var_expr",
  [sym_qubit_zero] = "qubit_zero",
  [sym_qubit_one] = "qubit_one",
  [sym__expr] = "_expr",
  [sym__binary_expr] = "_binary_expr",
  [sym_add] = "add",
  [sym_sub] = "sub",
  [sym_mul] = "mul",
  [sym_div] = "div",
  [sym_exp] = "exp",
  [sym__var_fn] = "_var_fn",
  [sym_sin] = "sin",
  [sym_cos] = "cos",
  [sym_tan] = "tan",
  [sym_root] = "root",
  [sym__constant] = "_constant",
  [sym__qc_fn] = "_qc_fn",
  [sym_measure] = "measure",
  [sym_pauli_x] = "pauli_x",
  [sym_pauli_y] = "pauli_y",
  [sym_pauli_z] = "pauli_z",
  [sym_hadamard] = "hadamard",
  [sym_phase] = "phase",
  [sym_pi_by_8] = "pi_by_8",
  [sym_controlled_not] = "controlled_not",
  [sym_controlled_z] = "controlled_z",
  [sym_swap] = "swap",
  [sym_toffoli] = "toffoli",
  [sym__comment] = "_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_var_name] = sym_var_name,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_number] = sym_number,
  [sym_uint] = sym_uint,
  [anon_sym_PIPE0_GT] = anon_sym_PIPE0_GT,
  [anon_sym_PIPE1_GT] = anon_sym_PIPE1_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_sin_LPAREN] = anon_sym_sin_LPAREN,
  [anon_sym_cos_LPAREN] = anon_sym_cos_LPAREN,
  [anon_sym_tan_LPAREN] = anon_sym_tan_LPAREN,
  [anon_sym_root_LPAREN] = anon_sym_root_LPAREN,
  [sym_pi] = sym_pi,
  [sym_imag] = sym_imag,
  [sym_euler] = sym_euler,
  [anon_sym_measure_LPAREN] = anon_sym_measure_LPAREN,
  [anon_sym_x_LPAREN] = anon_sym_x_LPAREN,
  [anon_sym_y_LPAREN] = anon_sym_y_LPAREN,
  [anon_sym_z_LPAREN] = anon_sym_z_LPAREN,
  [anon_sym_hadamard_LPAREN] = anon_sym_hadamard_LPAREN,
  [anon_sym_phase_LPAREN] = anon_sym_phase_LPAREN,
  [anon_sym_pi_8_LPAREN] = anon_sym_pi_8_LPAREN,
  [anon_sym_cnot_LPAREN] = anon_sym_cnot_LPAREN,
  [anon_sym_cz_LPAREN] = anon_sym_cz_LPAREN,
  [anon_sym_swap_LPAREN] = anon_sym_swap_LPAREN,
  [anon_sym_toffoli_LPAREN] = anon_sym_toffoli_LPAREN,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym__comment_token1] = aux_sym__comment_token1,
  [sym_source_file] = sym_source_file,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_var_expr] = sym_var_expr,
  [sym_qubit_zero] = sym_qubit_zero,
  [sym_qubit_one] = sym_qubit_one,
  [sym__expr] = sym__expr,
  [sym__binary_expr] = sym__binary_expr,
  [sym_add] = sym_add,
  [sym_sub] = sym_sub,
  [sym_mul] = sym_mul,
  [sym_div] = sym_div,
  [sym_exp] = sym_exp,
  [sym__var_fn] = sym__var_fn,
  [sym_sin] = sym_sin,
  [sym_cos] = sym_cos,
  [sym_tan] = sym_tan,
  [sym_root] = sym_root,
  [sym__constant] = sym__constant,
  [sym__qc_fn] = sym__qc_fn,
  [sym_measure] = sym_measure,
  [sym_pauli_x] = sym_pauli_x,
  [sym_pauli_y] = sym_pauli_y,
  [sym_pauli_z] = sym_pauli_z,
  [sym_hadamard] = sym_hadamard,
  [sym_phase] = sym_phase,
  [sym_pi_by_8] = sym_pi_by_8,
  [sym_controlled_not] = sym_controlled_not,
  [sym_controlled_z] = sym_controlled_z,
  [sym_swap] = sym_swap,
  [sym_toffoli] = sym_toffoli,
  [sym__comment] = sym__comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_var_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_uint] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE0_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE1_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sin_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cos_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tan_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_root_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_pi] = {
    .visible = true,
    .named = true,
  },
  [sym_imag] = {
    .visible = true,
    .named = true,
  },
  [sym_euler] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_measure_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_y_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_z_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hadamard_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_phase_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pi_8_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cnot_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cz_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_swap_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_toffoli_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_var_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_qubit_zero] = {
    .visible = true,
    .named = true,
  },
  [sym_qubit_one] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym__binary_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym_sub] = {
    .visible = true,
    .named = true,
  },
  [sym_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_exp] = {
    .visible = true,
    .named = true,
  },
  [sym__var_fn] = {
    .visible = false,
    .named = true,
  },
  [sym_sin] = {
    .visible = true,
    .named = true,
  },
  [sym_cos] = {
    .visible = true,
    .named = true,
  },
  [sym_tan] = {
    .visible = true,
    .named = true,
  },
  [sym_root] = {
    .visible = true,
    .named = true,
  },
  [sym__constant] = {
    .visible = false,
    .named = true,
  },
  [sym__qc_fn] = {
    .visible = false,
    .named = true,
  },
  [sym_measure] = {
    .visible = true,
    .named = true,
  },
  [sym_pauli_x] = {
    .visible = true,
    .named = true,
  },
  [sym_pauli_y] = {
    .visible = true,
    .named = true,
  },
  [sym_pauli_z] = {
    .visible = true,
    .named = true,
  },
  [sym_hadamard] = {
    .visible = true,
    .named = true,
  },
  [sym_phase] = {
    .visible = true,
    .named = true,
  },
  [sym_pi_by_8] = {
    .visible = true,
    .named = true,
  },
  [sym_controlled_not] = {
    .visible = true,
    .named = true,
  },
  [sym_controlled_z] = {
    .visible = true,
    .named = true,
  },
  [sym_swap] = {
    .visible = true,
    .named = true,
  },
  [sym_toffoli] = {
    .visible = true,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg = 1,
  field_arg1 = 2,
  field_arg2 = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg] = "arg",
  [field_arg1] = "arg1",
  [field_arg2] = "arg2",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_arg, 1},
  [1] =
    {field_arg1, 0},
    {field_arg2, 2},
  [3] =
    {field_arg1, 1},
    {field_arg2, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '(', 88,
        ')', 89,
        '*', 92,
        '+', 90,
        ',', 82,
        '-', 91,
        '/', 93,
        '=', 24,
        'E', 104,
        'I', 102,
        'P', 41,
        '^', 94,
        'c', 62,
        'h', 43,
        'm', 52,
        'p', 57,
        'r', 70,
        's', 58,
        't', 49,
        'x', 25,
        'y', 26,
        'z', 27,
        '|', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'w')) ADVANCE(81);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '(', 88,
        '-', 20,
        '/', 6,
        'E', 103,
        'I', 101,
        'P', 10,
        'c', 15,
        'r', 17,
        's', 12,
        't', 11,
        '|', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(96);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(95);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(97);
      END_STATE();
    case 5:
      if (lookahead == '(') ADVANCE(98);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(116);
      END_STATE();
    case 7:
      if (lookahead == '0') ADVANCE(8);
      if (lookahead == '1') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(86);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(87);
      END_STATE();
    case 10:
      if (lookahead == 'I') ADVANCE(99);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(3);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(2);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(5);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        ',', 82,
        '/', 6,
        'c', 63,
        'h', 43,
        'm', 52,
        'p', 57,
        's', 80,
        't', 66,
        'x', 25,
        'y', 26,
        'z', 27,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'w')) ADVANCE(81);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(113);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(111);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(110);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(109);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '8') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'I') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '_') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'a') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'a') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'a') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'a') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'a') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'a') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'a') ADVANCE(65);
      if (lookahead == 'o') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'd') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'd') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'e') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'e') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'e') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'f') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'f') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'h') ADVANCE(48);
      if (lookahead == 'i') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'i') ADVANCE(64);
      if (lookahead == 'w') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'i') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'l') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'm') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'n') ADVANCE(67);
      if (lookahead == 'o') ADVANCE(76);
      if (lookahead == 'z') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(81);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'n') ADVANCE(67);
      if (lookahead == 'z') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(81);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'n') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'n') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'o') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'o') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'o') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'o') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'o') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'p') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'r') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'r') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 's') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 's') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 's') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 't') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 't') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'u') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'w') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_var_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_uint);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_PIPE0_GT);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_PIPE1_GT);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(116);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_sin_LPAREN);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_cos_LPAREN);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_tan_LPAREN);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_root_LPAREN);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_pi);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_pi);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_imag);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_imag);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_euler);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_euler);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_measure_LPAREN);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_x_LPAREN);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_y_LPAREN);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_z_LPAREN);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_hadamard_LPAREN);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_phase_LPAREN);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_pi_8_LPAREN);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_cnot_LPAREN);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_cz_LPAREN);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_swap_LPAREN);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_toffoli_LPAREN);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(120);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym__comment_token1);
      if (lookahead == '/') ADVANCE(119);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(118);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(120);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym__comment_token1);
      if (lookahead == '/') ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(120);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym__comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(120);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 22},
  [2] = {.lex_state = 22},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 22},
  [20] = {.lex_state = 22},
  [21] = {.lex_state = 22},
  [22] = {.lex_state = 22},
  [23] = {.lex_state = 22},
  [24] = {.lex_state = 22},
  [25] = {.lex_state = 22},
  [26] = {.lex_state = 22},
  [27] = {.lex_state = 22},
  [28] = {.lex_state = 22},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 22},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 22},
  [73] = {.lex_state = 22},
  [74] = {.lex_state = 22},
  [75] = {.lex_state = 22},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 22},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 22},
  [83] = {.lex_state = 22},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 22},
  [87] = {.lex_state = 22},
  [88] = {.lex_state = 22},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 118},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 22},
  [97] = {.lex_state = 22},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 22},
  [100] = {.lex_state = 22},
  [101] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym__comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_var_name] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_uint] = ACTIONS(1),
    [anon_sym_PIPE0_GT] = ACTIONS(1),
    [anon_sym_PIPE1_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_sin_LPAREN] = ACTIONS(1),
    [anon_sym_cos_LPAREN] = ACTIONS(1),
    [anon_sym_tan_LPAREN] = ACTIONS(1),
    [anon_sym_root_LPAREN] = ACTIONS(1),
    [sym_pi] = ACTIONS(1),
    [sym_imag] = ACTIONS(1),
    [sym_euler] = ACTIONS(1),
    [anon_sym_measure_LPAREN] = ACTIONS(1),
    [anon_sym_x_LPAREN] = ACTIONS(1),
    [anon_sym_y_LPAREN] = ACTIONS(1),
    [anon_sym_z_LPAREN] = ACTIONS(1),
    [anon_sym_hadamard_LPAREN] = ACTIONS(1),
    [anon_sym_phase_LPAREN] = ACTIONS(1),
    [anon_sym_pi_8_LPAREN] = ACTIONS(1),
    [anon_sym_cnot_LPAREN] = ACTIONS(1),
    [anon_sym_cz_LPAREN] = ACTIONS(1),
    [anon_sym_swap_LPAREN] = ACTIONS(1),
    [anon_sym_toffoli_LPAREN] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(95),
    [sym_variable_declaration] = STATE(28),
    [sym__comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_var_name] = ACTIONS(5),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 20,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 1,
      sym_var_name,
    ACTIONS(11), 1,
      anon_sym_measure_LPAREN,
    ACTIONS(13), 1,
      anon_sym_x_LPAREN,
    ACTIONS(15), 1,
      anon_sym_y_LPAREN,
    ACTIONS(17), 1,
      anon_sym_z_LPAREN,
    ACTIONS(19), 1,
      anon_sym_hadamard_LPAREN,
    ACTIONS(21), 1,
      anon_sym_phase_LPAREN,
    ACTIONS(23), 1,
      anon_sym_pi_8_LPAREN,
    ACTIONS(25), 1,
      anon_sym_cnot_LPAREN,
    ACTIONS(27), 1,
      anon_sym_cz_LPAREN,
    ACTIONS(29), 1,
      anon_sym_swap_LPAREN,
    ACTIONS(31), 1,
      anon_sym_toffoli_LPAREN,
    STATE(2), 1,
      sym__comment,
    STATE(4), 1,
      aux_sym_source_file_repeat2,
    STATE(19), 1,
      aux_sym_source_file_repeat1,
    STATE(28), 1,
      sym_variable_declaration,
    STATE(33), 1,
      sym__qc_fn,
    STATE(37), 11,
      sym_measure,
      sym_pauli_x,
      sym_pauli_y,
      sym_pauli_z,
      sym_hadamard,
      sym_phase,
      sym_pi_by_8,
      sym_controlled_not,
      sym_controlled_z,
      sym_swap,
      sym_toffoli,
  [71] = 18,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_PIPE0_GT,
    ACTIONS(37), 1,
      anon_sym_PIPE1_GT,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(3), 1,
      sym__comment,
    STATE(24), 1,
      sym_qubit_zero,
    STATE(25), 1,
      sym_qubit_one,
    STATE(27), 1,
      sym_var_expr,
    STATE(57), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [137] = 17,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_measure_LPAREN,
    ACTIONS(13), 1,
      anon_sym_x_LPAREN,
    ACTIONS(15), 1,
      anon_sym_y_LPAREN,
    ACTIONS(17), 1,
      anon_sym_z_LPAREN,
    ACTIONS(19), 1,
      anon_sym_hadamard_LPAREN,
    ACTIONS(21), 1,
      anon_sym_phase_LPAREN,
    ACTIONS(23), 1,
      anon_sym_pi_8_LPAREN,
    ACTIONS(25), 1,
      anon_sym_cnot_LPAREN,
    ACTIONS(27), 1,
      anon_sym_cz_LPAREN,
    ACTIONS(29), 1,
      anon_sym_swap_LPAREN,
    ACTIONS(31), 1,
      anon_sym_toffoli_LPAREN,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym__comment,
    STATE(5), 1,
      aux_sym_source_file_repeat2,
    STATE(33), 1,
      sym__qc_fn,
    STATE(37), 11,
      sym_measure,
      sym_pauli_x,
      sym_pauli_y,
      sym_pauli_z,
      sym_hadamard,
      sym_phase,
      sym_pi_by_8,
      sym_controlled_not,
      sym_controlled_z,
      sym_swap,
      sym_toffoli,
  [199] = 16,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 1,
      anon_sym_measure_LPAREN,
    ACTIONS(58), 1,
      anon_sym_x_LPAREN,
    ACTIONS(61), 1,
      anon_sym_y_LPAREN,
    ACTIONS(64), 1,
      anon_sym_z_LPAREN,
    ACTIONS(67), 1,
      anon_sym_hadamard_LPAREN,
    ACTIONS(70), 1,
      anon_sym_phase_LPAREN,
    ACTIONS(73), 1,
      anon_sym_pi_8_LPAREN,
    ACTIONS(76), 1,
      anon_sym_cnot_LPAREN,
    ACTIONS(79), 1,
      anon_sym_cz_LPAREN,
    ACTIONS(82), 1,
      anon_sym_swap_LPAREN,
    ACTIONS(85), 1,
      anon_sym_toffoli_LPAREN,
    STATE(33), 1,
      sym__qc_fn,
    STATE(5), 2,
      sym__comment,
      aux_sym_source_file_repeat2,
    STATE(37), 11,
      sym_measure,
      sym_pauli_x,
      sym_pauli_y,
      sym_pauli_z,
      sym_hadamard,
      sym_phase,
      sym_pi_by_8,
      sym_controlled_not,
      sym_controlled_z,
      sym_swap,
      sym_toffoli,
  [259] = 15,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_PIPE0_GT,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(6), 1,
      sym__comment,
    STATE(26), 1,
      sym_qubit_zero,
    STATE(61), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [316] = 15,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_PIPE1_GT,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(7), 1,
      sym__comment,
    STATE(26), 1,
      sym_qubit_one,
    STATE(60), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [373] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(8), 1,
      sym__comment,
    STATE(65), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [424] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(9), 1,
      sym__comment,
    STATE(63), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [475] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(10), 1,
      sym__comment,
    STATE(58), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [526] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(11), 1,
      sym__comment,
    STATE(62), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [577] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(12), 1,
      sym__comment,
    STATE(64), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [628] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(13), 1,
      sym__comment,
    STATE(59), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [679] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(14), 1,
      sym__comment,
    STATE(48), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [730] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(15), 1,
      sym__comment,
    STATE(55), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [781] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(16), 1,
      sym__comment,
    STATE(50), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [832] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(17), 1,
      sym__comment,
    STATE(51), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [883] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(18), 1,
      sym__comment,
    STATE(52), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [934] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(90), 1,
      sym_var_name,
    STATE(28), 1,
      sym_variable_declaration,
    STATE(19), 2,
      sym__comment,
      aux_sym_source_file_repeat1,
    ACTIONS(88), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [962] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(95), 1,
      sym_var_name,
    STATE(20), 1,
      sym__comment,
    ACTIONS(93), 13,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [987] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(99), 1,
      sym_var_name,
    STATE(21), 1,
      sym__comment,
    ACTIONS(97), 13,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1012] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(103), 1,
      sym_var_name,
    STATE(22), 1,
      sym__comment,
    ACTIONS(101), 13,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1037] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(107), 1,
      sym_var_name,
    STATE(23), 1,
      sym__comment,
    ACTIONS(105), 13,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1062] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(111), 1,
      sym_var_name,
    ACTIONS(113), 1,
      anon_sym_COMMA,
    STATE(24), 1,
      sym__comment,
    ACTIONS(109), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1089] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(111), 1,
      sym_var_name,
    ACTIONS(115), 1,
      anon_sym_COMMA,
    STATE(25), 1,
      sym__comment,
    ACTIONS(109), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1116] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(119), 1,
      sym_var_name,
    STATE(26), 1,
      sym__comment,
    ACTIONS(117), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1140] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(123), 1,
      sym_var_name,
    STATE(27), 1,
      sym__comment,
    ACTIONS(121), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1164] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(127), 1,
      sym_var_name,
    STATE(28), 1,
      sym__comment,
    ACTIONS(125), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1188] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(29), 1,
      sym__comment,
    ACTIONS(129), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1209] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(30), 1,
      sym__comment,
    ACTIONS(131), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1230] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(31), 1,
      sym__comment,
    ACTIONS(133), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1251] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(32), 1,
      sym__comment,
    ACTIONS(135), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1272] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(33), 1,
      sym__comment,
    ACTIONS(137), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1293] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(34), 1,
      sym__comment,
    ACTIONS(139), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1314] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(35), 1,
      sym__comment,
    ACTIONS(141), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1335] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(36), 1,
      sym__comment,
    ACTIONS(143), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1356] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(37), 1,
      sym__comment,
    ACTIONS(145), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1377] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(38), 1,
      sym__comment,
    ACTIONS(147), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1398] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(39), 1,
      sym__comment,
    ACTIONS(149), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1419] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(40), 1,
      sym__comment,
    ACTIONS(151), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1440] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(41), 1,
      sym__comment,
    ACTIONS(153), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1461] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(42), 1,
      sym__comment,
    ACTIONS(155), 12,
      ts_builtin_sym_end,
      anon_sym_measure_LPAREN,
      anon_sym_x_LPAREN,
      anon_sym_y_LPAREN,
      anon_sym_z_LPAREN,
      anon_sym_hadamard_LPAREN,
      anon_sym_phase_LPAREN,
      anon_sym_pi_8_LPAREN,
      anon_sym_cnot_LPAREN,
      anon_sym_cz_LPAREN,
      anon_sym_swap_LPAREN,
      anon_sym_toffoli_LPAREN,
  [1482] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(159), 1,
      anon_sym_SLASH,
    STATE(43), 1,
      sym__comment,
    ACTIONS(157), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1502] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(163), 1,
      anon_sym_SLASH,
    STATE(44), 1,
      sym__comment,
    ACTIONS(161), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1522] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(167), 1,
      anon_sym_SLASH,
    STATE(45), 1,
      sym__comment,
    ACTIONS(165), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1542] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(171), 1,
      anon_sym_SLASH,
    STATE(46), 1,
      sym__comment,
    ACTIONS(169), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1562] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(175), 1,
      anon_sym_SLASH,
    STATE(47), 1,
      sym__comment,
    ACTIONS(173), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1582] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(181), 1,
      anon_sym_SLASH,
    ACTIONS(183), 1,
      anon_sym_CARET,
    STATE(48), 1,
      sym__comment,
    ACTIONS(177), 6,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1606] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(187), 1,
      anon_sym_SLASH,
    STATE(49), 1,
      sym__comment,
    ACTIONS(185), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1626] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(183), 1,
      anon_sym_CARET,
    ACTIONS(191), 1,
      anon_sym_SLASH,
    STATE(50), 1,
      sym__comment,
    ACTIONS(189), 7,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1648] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(183), 1,
      anon_sym_CARET,
    ACTIONS(195), 1,
      anon_sym_SLASH,
    STATE(51), 1,
      sym__comment,
    ACTIONS(193), 7,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1670] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(199), 1,
      anon_sym_SLASH,
    STATE(52), 1,
      sym__comment,
    ACTIONS(197), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1690] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(203), 1,
      anon_sym_SLASH,
    STATE(53), 1,
      sym__comment,
    ACTIONS(201), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1710] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(207), 1,
      anon_sym_SLASH,
    STATE(54), 1,
      sym__comment,
    ACTIONS(205), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1730] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(181), 1,
      anon_sym_SLASH,
    ACTIONS(183), 1,
      anon_sym_CARET,
    STATE(55), 1,
      sym__comment,
    ACTIONS(209), 6,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1754] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(213), 1,
      anon_sym_SLASH,
    STATE(56), 1,
      sym__comment,
    ACTIONS(211), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1774] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(181), 1,
      anon_sym_SLASH,
    ACTIONS(183), 1,
      anon_sym_CARET,
    ACTIONS(215), 1,
      anon_sym_PIPE0_GT,
    ACTIONS(217), 1,
      anon_sym_PIPE1_GT,
    ACTIONS(219), 1,
      anon_sym_PLUS,
    ACTIONS(221), 1,
      anon_sym_DASH,
    STATE(57), 1,
      sym__comment,
  [1802] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(181), 1,
      anon_sym_SLASH,
    ACTIONS(183), 1,
      anon_sym_CARET,
    ACTIONS(219), 1,
      anon_sym_PLUS,
    ACTIONS(221), 1,
      anon_sym_DASH,
    ACTIONS(223), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      sym__comment,
  [1827] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(181), 1,
      anon_sym_SLASH,
    ACTIONS(183), 1,
      anon_sym_CARET,
    ACTIONS(219), 1,
      anon_sym_PLUS,
    ACTIONS(221), 1,
      anon_sym_DASH,
    ACTIONS(225), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      sym__comment,
  [1852] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(181), 1,
      anon_sym_SLASH,
    ACTIONS(183), 1,
      anon_sym_CARET,
    ACTIONS(217), 1,
      anon_sym_PIPE1_GT,
    ACTIONS(219), 1,
      anon_sym_PLUS,
    ACTIONS(221), 1,
      anon_sym_DASH,
    STATE(60), 1,
      sym__comment,
  [1877] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(181), 1,
      anon_sym_SLASH,
    ACTIONS(183), 1,
      anon_sym_CARET,
    ACTIONS(215), 1,
      anon_sym_PIPE0_GT,
    ACTIONS(219), 1,
      anon_sym_PLUS,
    ACTIONS(221), 1,
      anon_sym_DASH,
    STATE(61), 1,
      sym__comment,
  [1902] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(181), 1,
      anon_sym_SLASH,
    ACTIONS(183), 1,
      anon_sym_CARET,
    ACTIONS(219), 1,
      anon_sym_PLUS,
    ACTIONS(221), 1,
      anon_sym_DASH,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      sym__comment,
  [1927] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(181), 1,
      anon_sym_SLASH,
    ACTIONS(183), 1,
      anon_sym_CARET,
    ACTIONS(219), 1,
      anon_sym_PLUS,
    ACTIONS(221), 1,
      anon_sym_DASH,
    ACTIONS(229), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      sym__comment,
  [1952] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(181), 1,
      anon_sym_SLASH,
    ACTIONS(183), 1,
      anon_sym_CARET,
    ACTIONS(219), 1,
      anon_sym_PLUS,
    ACTIONS(221), 1,
      anon_sym_DASH,
    ACTIONS(231), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      sym__comment,
  [1977] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(181), 1,
      anon_sym_SLASH,
    ACTIONS(183), 1,
      anon_sym_CARET,
    ACTIONS(219), 1,
      anon_sym_PLUS,
    ACTIONS(221), 1,
      anon_sym_DASH,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      sym__comment,
  [2002] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(235), 1,
      sym_uint,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      sym__comment,
  [2015] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      sym__comment,
  [2025] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      sym__comment,
  [2035] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(243), 1,
      sym_var_name,
    STATE(69), 1,
      sym__comment,
  [2045] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      sym__comment,
  [2055] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(247), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      sym__comment,
  [2065] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(249), 1,
      sym_var_name,
    STATE(72), 1,
      sym__comment,
  [2075] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(251), 1,
      sym_var_name,
    STATE(73), 1,
      sym__comment,
  [2085] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(253), 1,
      sym_var_name,
    STATE(74), 1,
      sym__comment,
  [2095] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(255), 1,
      sym_var_name,
    STATE(75), 1,
      sym__comment,
  [2105] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(257), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      sym__comment,
  [2115] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(259), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      sym__comment,
  [2125] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(261), 1,
      sym_var_name,
    STATE(78), 1,
      sym__comment,
  [2135] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      sym__comment,
  [2145] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      sym__comment,
  [2155] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(267), 1,
      anon_sym_COMMA,
    STATE(81), 1,
      sym__comment,
  [2165] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(269), 1,
      sym_var_name,
    STATE(82), 1,
      sym__comment,
  [2175] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(271), 1,
      sym_var_name,
    STATE(83), 1,
      sym__comment,
  [2185] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(273), 1,
      anon_sym_COMMA,
    STATE(84), 1,
      sym__comment,
  [2195] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      sym__comment,
  [2205] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(277), 1,
      sym_var_name,
    STATE(86), 1,
      sym__comment,
  [2215] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(279), 1,
      sym_var_name,
    STATE(87), 1,
      sym__comment,
  [2225] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(281), 1,
      sym_var_name,
    STATE(88), 1,
      sym__comment,
  [2235] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(283), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      sym__comment,
  [2245] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(285), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      sym__comment,
  [2255] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      sym__comment,
  [2265] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(289), 1,
      anon_sym_COMMA,
    STATE(92), 1,
      sym__comment,
  [2275] = 3,
    ACTIONS(291), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(293), 1,
      aux_sym__comment_token1,
    STATE(93), 1,
      sym__comment,
  [2285] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(295), 1,
      anon_sym_EQ,
    STATE(94), 1,
      sym__comment,
  [2295] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(297), 1,
      ts_builtin_sym_end,
    STATE(95), 1,
      sym__comment,
  [2305] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(299), 1,
      sym_var_name,
    STATE(96), 1,
      sym__comment,
  [2315] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(301), 1,
      sym_var_name,
    STATE(97), 1,
      sym__comment,
  [2325] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      sym__comment,
  [2335] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(305), 1,
      sym_var_name,
    STATE(99), 1,
      sym__comment,
  [2345] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(307), 1,
      sym_var_name,
    STATE(100), 1,
      sym__comment,
  [2355] = 1,
    ACTIONS(309), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 71,
  [SMALL_STATE(4)] = 137,
  [SMALL_STATE(5)] = 199,
  [SMALL_STATE(6)] = 259,
  [SMALL_STATE(7)] = 316,
  [SMALL_STATE(8)] = 373,
  [SMALL_STATE(9)] = 424,
  [SMALL_STATE(10)] = 475,
  [SMALL_STATE(11)] = 526,
  [SMALL_STATE(12)] = 577,
  [SMALL_STATE(13)] = 628,
  [SMALL_STATE(14)] = 679,
  [SMALL_STATE(15)] = 730,
  [SMALL_STATE(16)] = 781,
  [SMALL_STATE(17)] = 832,
  [SMALL_STATE(18)] = 883,
  [SMALL_STATE(19)] = 934,
  [SMALL_STATE(20)] = 962,
  [SMALL_STATE(21)] = 987,
  [SMALL_STATE(22)] = 1012,
  [SMALL_STATE(23)] = 1037,
  [SMALL_STATE(24)] = 1062,
  [SMALL_STATE(25)] = 1089,
  [SMALL_STATE(26)] = 1116,
  [SMALL_STATE(27)] = 1140,
  [SMALL_STATE(28)] = 1164,
  [SMALL_STATE(29)] = 1188,
  [SMALL_STATE(30)] = 1209,
  [SMALL_STATE(31)] = 1230,
  [SMALL_STATE(32)] = 1251,
  [SMALL_STATE(33)] = 1272,
  [SMALL_STATE(34)] = 1293,
  [SMALL_STATE(35)] = 1314,
  [SMALL_STATE(36)] = 1335,
  [SMALL_STATE(37)] = 1356,
  [SMALL_STATE(38)] = 1377,
  [SMALL_STATE(39)] = 1398,
  [SMALL_STATE(40)] = 1419,
  [SMALL_STATE(41)] = 1440,
  [SMALL_STATE(42)] = 1461,
  [SMALL_STATE(43)] = 1482,
  [SMALL_STATE(44)] = 1502,
  [SMALL_STATE(45)] = 1522,
  [SMALL_STATE(46)] = 1542,
  [SMALL_STATE(47)] = 1562,
  [SMALL_STATE(48)] = 1582,
  [SMALL_STATE(49)] = 1606,
  [SMALL_STATE(50)] = 1626,
  [SMALL_STATE(51)] = 1648,
  [SMALL_STATE(52)] = 1670,
  [SMALL_STATE(53)] = 1690,
  [SMALL_STATE(54)] = 1710,
  [SMALL_STATE(55)] = 1730,
  [SMALL_STATE(56)] = 1754,
  [SMALL_STATE(57)] = 1774,
  [SMALL_STATE(58)] = 1802,
  [SMALL_STATE(59)] = 1827,
  [SMALL_STATE(60)] = 1852,
  [SMALL_STATE(61)] = 1877,
  [SMALL_STATE(62)] = 1902,
  [SMALL_STATE(63)] = 1927,
  [SMALL_STATE(64)] = 1952,
  [SMALL_STATE(65)] = 1977,
  [SMALL_STATE(66)] = 2002,
  [SMALL_STATE(67)] = 2015,
  [SMALL_STATE(68)] = 2025,
  [SMALL_STATE(69)] = 2035,
  [SMALL_STATE(70)] = 2045,
  [SMALL_STATE(71)] = 2055,
  [SMALL_STATE(72)] = 2065,
  [SMALL_STATE(73)] = 2075,
  [SMALL_STATE(74)] = 2085,
  [SMALL_STATE(75)] = 2095,
  [SMALL_STATE(76)] = 2105,
  [SMALL_STATE(77)] = 2115,
  [SMALL_STATE(78)] = 2125,
  [SMALL_STATE(79)] = 2135,
  [SMALL_STATE(80)] = 2145,
  [SMALL_STATE(81)] = 2155,
  [SMALL_STATE(82)] = 2165,
  [SMALL_STATE(83)] = 2175,
  [SMALL_STATE(84)] = 2185,
  [SMALL_STATE(85)] = 2195,
  [SMALL_STATE(86)] = 2205,
  [SMALL_STATE(87)] = 2215,
  [SMALL_STATE(88)] = 2225,
  [SMALL_STATE(89)] = 2235,
  [SMALL_STATE(90)] = 2245,
  [SMALL_STATE(91)] = 2255,
  [SMALL_STATE(92)] = 2265,
  [SMALL_STATE(93)] = 2275,
  [SMALL_STATE(94)] = 2285,
  [SMALL_STATE(95)] = 2295,
  [SMALL_STATE(96)] = 2305,
  [SMALL_STATE(97)] = 2315,
  [SMALL_STATE(98)] = 2325,
  [SMALL_STATE(99)] = 2335,
  [SMALL_STATE(100)] = 2345,
  [SMALL_STATE(101)] = 2355,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(66),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(86),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(87),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(97),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(99),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(78),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(100),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(69),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(82),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(83),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(88),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qubit_zero, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qubit_zero, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qubit_zero, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qubit_zero, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qubit_one, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qubit_one, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qubit_one, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qubit_one, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_expr, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_expr, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_expr, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_expr, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pauli_y, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pi_by_8, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_phase, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_measure, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pauli_x, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_measure, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hadamard, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__qc_fn, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pauli_z, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_swap, 5, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_controlled_z, 5, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_controlled_not, 5, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_toffoli, 7, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__var_fn, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__var_fn, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sin, 3, 0, 1),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sin, 3, 0, 1),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__constant, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__constant, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add, 3, 0, 2),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cos, 3, 0, 1),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cos, 3, 0, 1),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul, 3, 0, 2),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mul, 3, 0, 2),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 3, 0, 2),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 3, 0, 2),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exp, 3, 0, 2),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exp, 3, 0, 2),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binary_expr, 1, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__binary_expr, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tan, 3, 0, 1),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tan, 3, 0, 1),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub, 3, 0, 2),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root, 5, 0, 3),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root, 5, 0, 3),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [291] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [293] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [297] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_qc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "qc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
