/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 113
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 68
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  sym_var_name = 2,
  anon_sym_COMMA = 3,
  sym_number = 4,
  sym_uint = 5,
  anon_sym_PIPE0_GT = 6,
  anon_sym_PIPE1_GT = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  anon_sym_PLUS = 10,
  anon_sym_DASH = 11,
  anon_sym_STAR = 12,
  anon_sym_SLASH = 13,
  anon_sym_CARET = 14,
  anon_sym_sin_LPAREN = 15,
  anon_sym_cos_LPAREN = 16,
  anon_sym_tan_LPAREN = 17,
  anon_sym_root_LPAREN = 18,
  sym_pi = 19,
  sym_imag = 20,
  sym_euler = 21,
  anon_sym_measure = 22,
  anon_sym_x = 23,
  anon_sym_y = 24,
  anon_sym_z = 25,
  anon_sym_hadamard = 26,
  anon_sym_phase = 27,
  anon_sym_pi_8 = 28,
  anon_sym_cnot = 29,
  anon_sym_cz = 30,
  anon_sym_swap = 31,
  anon_sym_toffoli = 32,
  anon_sym_SLASH_SLASH = 33,
  aux_sym_comment_token1 = 34,
  sym_source_file = 35,
  sym_variable_declaration = 36,
  sym_var_expr = 37,
  sym_qubit_zero = 38,
  sym_qubit_one = 39,
  sym__expr = 40,
  sym__binary_expr = 41,
  sym_add = 42,
  sym_sub = 43,
  sym_mul = 44,
  sym_div = 45,
  sym_exp = 46,
  sym__var_fn = 47,
  sym_sin = 48,
  sym_cos = 49,
  sym_tan = 50,
  sym_root = 51,
  sym__constant = 52,
  sym__qc_fn = 53,
  sym_measure = 54,
  sym_pauli_x = 55,
  sym_pauli_y = 56,
  sym_pauli_z = 57,
  sym_hadamard = 58,
  sym_phase = 59,
  sym_pi_by_8 = 60,
  sym_controlled_not = 61,
  sym_controlled_z = 62,
  sym_swap = 63,
  sym_toffoli = 64,
  sym_comment = 65,
  aux_sym_source_file_repeat1 = 66,
  aux_sym_source_file_repeat2 = 67,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [sym_var_name] = "var_name",
  [anon_sym_COMMA] = ",",
  [sym_number] = "number",
  [sym_uint] = "uint",
  [anon_sym_PIPE0_GT] = "|0>",
  [anon_sym_PIPE1_GT] = "|1>",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_CARET] = "^",
  [anon_sym_sin_LPAREN] = "sin(",
  [anon_sym_cos_LPAREN] = "cos(",
  [anon_sym_tan_LPAREN] = "tan(",
  [anon_sym_root_LPAREN] = "root(",
  [sym_pi] = "pi",
  [sym_imag] = "imag",
  [sym_euler] = "euler",
  [anon_sym_measure] = "measure",
  [anon_sym_x] = "x",
  [anon_sym_y] = "y",
  [anon_sym_z] = "z",
  [anon_sym_hadamard] = "hadamard",
  [anon_sym_phase] = "phase",
  [anon_sym_pi_8] = "pi_8",
  [anon_sym_cnot] = "cnot",
  [anon_sym_cz] = "cz",
  [anon_sym_swap] = "swap",
  [anon_sym_toffoli] = "toffoli",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_source_file] = "source_file",
  [sym_variable_declaration] = "variable_declaration",
  [sym_var_expr] = "var_expr",
  [sym_qubit_zero] = "qubit_zero",
  [sym_qubit_one] = "qubit_one",
  [sym__expr] = "_expr",
  [sym__binary_expr] = "_binary_expr",
  [sym_add] = "add",
  [sym_sub] = "sub",
  [sym_mul] = "mul",
  [sym_div] = "div",
  [sym_exp] = "exp",
  [sym__var_fn] = "_var_fn",
  [sym_sin] = "sin",
  [sym_cos] = "cos",
  [sym_tan] = "tan",
  [sym_root] = "root",
  [sym__constant] = "_constant",
  [sym__qc_fn] = "_qc_fn",
  [sym_measure] = "measure",
  [sym_pauli_x] = "pauli_x",
  [sym_pauli_y] = "pauli_y",
  [sym_pauli_z] = "pauli_z",
  [sym_hadamard] = "hadamard",
  [sym_phase] = "phase",
  [sym_pi_by_8] = "pi_by_8",
  [sym_controlled_not] = "controlled_not",
  [sym_controlled_z] = "controlled_z",
  [sym_swap] = "swap",
  [sym_toffoli] = "toffoli",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_var_name] = sym_var_name,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_number] = sym_number,
  [sym_uint] = sym_uint,
  [anon_sym_PIPE0_GT] = anon_sym_PIPE0_GT,
  [anon_sym_PIPE1_GT] = anon_sym_PIPE1_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_sin_LPAREN] = anon_sym_sin_LPAREN,
  [anon_sym_cos_LPAREN] = anon_sym_cos_LPAREN,
  [anon_sym_tan_LPAREN] = anon_sym_tan_LPAREN,
  [anon_sym_root_LPAREN] = anon_sym_root_LPAREN,
  [sym_pi] = sym_pi,
  [sym_imag] = sym_imag,
  [sym_euler] = sym_euler,
  [anon_sym_measure] = anon_sym_measure,
  [anon_sym_x] = anon_sym_x,
  [anon_sym_y] = anon_sym_y,
  [anon_sym_z] = anon_sym_z,
  [anon_sym_hadamard] = anon_sym_hadamard,
  [anon_sym_phase] = anon_sym_phase,
  [anon_sym_pi_8] = anon_sym_pi_8,
  [anon_sym_cnot] = anon_sym_cnot,
  [anon_sym_cz] = anon_sym_cz,
  [anon_sym_swap] = anon_sym_swap,
  [anon_sym_toffoli] = anon_sym_toffoli,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_var_expr] = sym_var_expr,
  [sym_qubit_zero] = sym_qubit_zero,
  [sym_qubit_one] = sym_qubit_one,
  [sym__expr] = sym__expr,
  [sym__binary_expr] = sym__binary_expr,
  [sym_add] = sym_add,
  [sym_sub] = sym_sub,
  [sym_mul] = sym_mul,
  [sym_div] = sym_div,
  [sym_exp] = sym_exp,
  [sym__var_fn] = sym__var_fn,
  [sym_sin] = sym_sin,
  [sym_cos] = sym_cos,
  [sym_tan] = sym_tan,
  [sym_root] = sym_root,
  [sym__constant] = sym__constant,
  [sym__qc_fn] = sym__qc_fn,
  [sym_measure] = sym_measure,
  [sym_pauli_x] = sym_pauli_x,
  [sym_pauli_y] = sym_pauli_y,
  [sym_pauli_z] = sym_pauli_z,
  [sym_hadamard] = sym_hadamard,
  [sym_phase] = sym_phase,
  [sym_pi_by_8] = sym_pi_by_8,
  [sym_controlled_not] = sym_controlled_not,
  [sym_controlled_z] = sym_controlled_z,
  [sym_swap] = sym_swap,
  [sym_toffoli] = sym_toffoli,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_var_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_uint] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE0_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE1_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sin_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cos_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tan_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_root_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_pi] = {
    .visible = true,
    .named = true,
  },
  [sym_imag] = {
    .visible = true,
    .named = true,
  },
  [sym_euler] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_measure] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_y] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_z] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hadamard] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_phase] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pi_8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cnot] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cz] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_swap] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_toffoli] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_var_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_qubit_zero] = {
    .visible = true,
    .named = true,
  },
  [sym_qubit_one] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym__binary_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym_sub] = {
    .visible = true,
    .named = true,
  },
  [sym_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_exp] = {
    .visible = true,
    .named = true,
  },
  [sym__var_fn] = {
    .visible = false,
    .named = true,
  },
  [sym_sin] = {
    .visible = true,
    .named = true,
  },
  [sym_cos] = {
    .visible = true,
    .named = true,
  },
  [sym_tan] = {
    .visible = true,
    .named = true,
  },
  [sym_root] = {
    .visible = true,
    .named = true,
  },
  [sym__constant] = {
    .visible = false,
    .named = true,
  },
  [sym__qc_fn] = {
    .visible = false,
    .named = true,
  },
  [sym_measure] = {
    .visible = true,
    .named = true,
  },
  [sym_pauli_x] = {
    .visible = true,
    .named = true,
  },
  [sym_pauli_y] = {
    .visible = true,
    .named = true,
  },
  [sym_pauli_z] = {
    .visible = true,
    .named = true,
  },
  [sym_hadamard] = {
    .visible = true,
    .named = true,
  },
  [sym_phase] = {
    .visible = true,
    .named = true,
  },
  [sym_pi_by_8] = {
    .visible = true,
    .named = true,
  },
  [sym_controlled_not] = {
    .visible = true,
    .named = true,
  },
  [sym_controlled_z] = {
    .visible = true,
    .named = true,
  },
  [sym_swap] = {
    .visible = true,
    .named = true,
  },
  [sym_toffoli] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg = 1,
  field_arg1 = 2,
  field_arg2 = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg] = "arg",
  [field_arg1] = "arg1",
  [field_arg2] = "arg2",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_arg, 1},
  [1] =
    {field_arg1, 0},
    {field_arg2, 2},
  [3] =
    {field_arg1, 1},
    {field_arg2, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '(', 78,
        ')', 79,
        '*', 82,
        '+', 80,
        ',', 72,
        '-', 81,
        '/', 83,
        '=', 25,
        'E', 94,
        'I', 92,
        'P', 31,
        '^', 84,
        'c', 52,
        'h', 33,
        'm', 44,
        'p', 47,
        'r', 60,
        's', 48,
        't', 39,
        'x', 96,
        'y', 97,
        'z', 98,
        '|', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'w')) ADVANCE(71);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '(', 78,
        '-', 21,
        '/', 6,
        'E', 93,
        'I', 91,
        'P', 11,
        'c', 16,
        'r', 18,
        's', 13,
        't', 12,
        '|', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(86);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(85);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(87);
      END_STATE();
    case 5:
      if (lookahead == '(') ADVANCE(88);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(106);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 8:
      if (lookahead == '0') ADVANCE(9);
      if (lookahead == '1') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(76);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(77);
      END_STATE();
    case 11:
      if (lookahead == 'I') ADVANCE(89);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(3);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(2);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(5);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        ',', 72,
        '/', 6,
        'c', 53,
        'h', 33,
        'm', 44,
        'p', 47,
        's', 70,
        't', 56,
        'x', 96,
        'y', 97,
        'z', 98,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'w')) ADVANCE(71);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '(') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '8') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'I') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '_') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'a') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'a') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'a') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'a') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'a') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'a') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'a') ADVANCE(55);
      if (lookahead == 'o') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'd') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'd') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'e') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'e') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'e') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'f') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'f') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'h') ADVANCE(38);
      if (lookahead == 'i') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'i') ADVANCE(54);
      if (lookahead == 'w') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'i') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'l') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'm') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'n') ADVANCE(57);
      if (lookahead == 'o') ADVANCE(64);
      if (lookahead == 'z') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(71);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'n') ADVANCE(57);
      if (lookahead == 'z') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(71);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'n') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'n') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'o') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'o') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'o') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'o') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'o') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'p') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'r') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'r') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 's') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 's') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 's') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 't') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 't') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'u') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == 'w') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_var_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_uint);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_PIPE0_GT);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_PIPE1_GT);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(106);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_sin_LPAREN);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_cos_LPAREN);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_tan_LPAREN);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_root_LPAREN);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_pi);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_pi);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_imag);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_imag);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_euler);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_euler);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_measure);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_x);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_y);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_z);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_hadamard);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_phase);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_pi_8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_cnot);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_cz);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_swap);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_toffoli);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(110);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(109);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(108);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(110);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(107);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(110);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(110);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 23},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 23},
  [20] = {.lex_state = 23},
  [21] = {.lex_state = 23},
  [22] = {.lex_state = 23},
  [23] = {.lex_state = 23},
  [24] = {.lex_state = 23},
  [25] = {.lex_state = 23},
  [26] = {.lex_state = 23},
  [27] = {.lex_state = 23},
  [28] = {.lex_state = 23},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 7},
  [77] = {.lex_state = 7},
  [78] = {.lex_state = 7},
  [79] = {.lex_state = 7},
  [80] = {.lex_state = 7},
  [81] = {.lex_state = 7},
  [82] = {.lex_state = 7},
  [83] = {.lex_state = 7},
  [84] = {.lex_state = 7},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 108},
  [96] = {.lex_state = 7},
  [97] = {.lex_state = 7},
  [98] = {.lex_state = 7},
  [99] = {.lex_state = 7},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 7},
  [108] = {.lex_state = 7},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_var_name] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_uint] = ACTIONS(1),
    [anon_sym_PIPE0_GT] = ACTIONS(1),
    [anon_sym_PIPE1_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_sin_LPAREN] = ACTIONS(1),
    [anon_sym_cos_LPAREN] = ACTIONS(1),
    [anon_sym_tan_LPAREN] = ACTIONS(1),
    [anon_sym_root_LPAREN] = ACTIONS(1),
    [sym_pi] = ACTIONS(1),
    [sym_imag] = ACTIONS(1),
    [sym_euler] = ACTIONS(1),
    [anon_sym_measure] = ACTIONS(1),
    [anon_sym_x] = ACTIONS(1),
    [anon_sym_y] = ACTIONS(1),
    [anon_sym_z] = ACTIONS(1),
    [anon_sym_hadamard] = ACTIONS(1),
    [anon_sym_phase] = ACTIONS(1),
    [anon_sym_pi_8] = ACTIONS(1),
    [anon_sym_cnot] = ACTIONS(1),
    [anon_sym_cz] = ACTIONS(1),
    [anon_sym_swap] = ACTIONS(1),
    [anon_sym_toffoli] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(104),
    [sym_variable_declaration] = STATE(26),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_var_name] = ACTIONS(5),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 20,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 1,
      sym_var_name,
    ACTIONS(11), 1,
      anon_sym_measure,
    ACTIONS(13), 1,
      anon_sym_x,
    ACTIONS(15), 1,
      anon_sym_y,
    ACTIONS(17), 1,
      anon_sym_z,
    ACTIONS(19), 1,
      anon_sym_hadamard,
    ACTIONS(21), 1,
      anon_sym_phase,
    ACTIONS(23), 1,
      anon_sym_pi_8,
    ACTIONS(25), 1,
      anon_sym_cnot,
    ACTIONS(27), 1,
      anon_sym_cz,
    ACTIONS(29), 1,
      anon_sym_swap,
    ACTIONS(31), 1,
      anon_sym_toffoli,
    STATE(2), 1,
      sym_comment,
    STATE(4), 1,
      aux_sym_source_file_repeat2,
    STATE(19), 1,
      aux_sym_source_file_repeat1,
    STATE(26), 1,
      sym_variable_declaration,
    STATE(31), 1,
      sym__qc_fn,
    STATE(36), 11,
      sym_measure,
      sym_pauli_x,
      sym_pauli_y,
      sym_pauli_z,
      sym_hadamard,
      sym_phase,
      sym_pi_by_8,
      sym_controlled_not,
      sym_controlled_z,
      sym_swap,
      sym_toffoli,
  [71] = 18,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_PIPE0_GT,
    ACTIONS(37), 1,
      anon_sym_PIPE1_GT,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(3), 1,
      sym_comment,
    STATE(24), 1,
      sym_qubit_zero,
    STATE(25), 1,
      sym_qubit_one,
    STATE(27), 1,
      sym_var_expr,
    STATE(57), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [137] = 17,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      anon_sym_measure,
    ACTIONS(55), 1,
      anon_sym_x,
    ACTIONS(57), 1,
      anon_sym_y,
    ACTIONS(59), 1,
      anon_sym_z,
    ACTIONS(61), 1,
      anon_sym_hadamard,
    ACTIONS(63), 1,
      anon_sym_phase,
    ACTIONS(65), 1,
      anon_sym_pi_8,
    ACTIONS(67), 1,
      anon_sym_cnot,
    ACTIONS(69), 1,
      anon_sym_cz,
    ACTIONS(71), 1,
      anon_sym_swap,
    ACTIONS(73), 1,
      anon_sym_toffoli,
    STATE(4), 1,
      sym_comment,
    STATE(5), 1,
      aux_sym_source_file_repeat2,
    STATE(31), 1,
      sym__qc_fn,
    STATE(36), 11,
      sym_measure,
      sym_pauli_x,
      sym_pauli_y,
      sym_pauli_z,
      sym_hadamard,
      sym_phase,
      sym_pi_by_8,
      sym_controlled_not,
      sym_controlled_z,
      sym_swap,
      sym_toffoli,
  [199] = 16,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 1,
      anon_sym_measure,
    ACTIONS(80), 1,
      anon_sym_x,
    ACTIONS(83), 1,
      anon_sym_y,
    ACTIONS(86), 1,
      anon_sym_z,
    ACTIONS(89), 1,
      anon_sym_hadamard,
    ACTIONS(92), 1,
      anon_sym_phase,
    ACTIONS(95), 1,
      anon_sym_pi_8,
    ACTIONS(98), 1,
      anon_sym_cnot,
    ACTIONS(101), 1,
      anon_sym_cz,
    ACTIONS(104), 1,
      anon_sym_swap,
    ACTIONS(107), 1,
      anon_sym_toffoli,
    STATE(31), 1,
      sym__qc_fn,
    STATE(5), 2,
      sym_comment,
      aux_sym_source_file_repeat2,
    STATE(36), 11,
      sym_measure,
      sym_pauli_x,
      sym_pauli_y,
      sym_pauli_z,
      sym_hadamard,
      sym_phase,
      sym_pi_by_8,
      sym_controlled_not,
      sym_controlled_z,
      sym_swap,
      sym_toffoli,
  [259] = 15,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_PIPE0_GT,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(6), 1,
      sym_comment,
    STATE(28), 1,
      sym_qubit_zero,
    STATE(60), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [316] = 15,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_PIPE1_GT,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(7), 1,
      sym_comment,
    STATE(28), 1,
      sym_qubit_one,
    STATE(58), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [373] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(8), 1,
      sym_comment,
    STATE(63), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [424] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(9), 1,
      sym_comment,
    STATE(61), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [475] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(10), 1,
      sym_comment,
    STATE(62), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [526] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(11), 1,
      sym_comment,
    STATE(65), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [577] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(12), 1,
      sym_comment,
    STATE(59), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [628] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(13), 1,
      sym_comment,
    STATE(48), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [679] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(14), 1,
      sym_comment,
    STATE(46), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [730] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(15), 1,
      sym_comment,
    STATE(49), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [781] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(16), 1,
      sym_comment,
    STATE(45), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [832] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(17), 1,
      sym_comment,
    STATE(47), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [883] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_sin_LPAREN,
    ACTIONS(43), 1,
      anon_sym_cos_LPAREN,
    ACTIONS(45), 1,
      anon_sym_tan_LPAREN,
    ACTIONS(47), 1,
      anon_sym_root_LPAREN,
    STATE(18), 1,
      sym_comment,
    STATE(64), 1,
      sym__expr,
    ACTIONS(49), 3,
      sym_pi,
      sym_imag,
      sym_euler,
    STATE(44), 3,
      sym__binary_expr,
      sym__var_fn,
      sym__constant,
    STATE(43), 4,
      sym_sin,
      sym_cos,
      sym_tan,
      sym_root,
    STATE(53), 5,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_exp,
  [934] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 1,
      sym_var_name,
    STATE(26), 1,
      sym_variable_declaration,
    STATE(19), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    ACTIONS(115), 11,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [964] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
    ACTIONS(119), 12,
      sym_var_name,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [989] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(121), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
    ACTIONS(123), 12,
      sym_var_name,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1014] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(22), 1,
      sym_comment,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
    ACTIONS(127), 12,
      sym_var_name,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1039] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(23), 1,
      sym_comment,
    ACTIONS(129), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
    ACTIONS(131), 12,
      sym_var_name,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1064] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
    ACTIONS(137), 1,
      anon_sym_COMMA,
    STATE(24), 1,
      sym_comment,
    ACTIONS(135), 12,
      sym_var_name,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1091] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
    ACTIONS(139), 1,
      anon_sym_COMMA,
    STATE(25), 1,
      sym_comment,
    ACTIONS(135), 12,
      sym_var_name,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1118] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    STATE(26), 1,
      sym_comment,
    ACTIONS(143), 12,
      sym_var_name,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1142] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    STATE(27), 1,
      sym_comment,
    ACTIONS(147), 12,
      sym_var_name,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1166] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    STATE(28), 1,
      sym_comment,
    ACTIONS(151), 12,
      sym_var_name,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1190] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(29), 1,
      sym_comment,
    ACTIONS(153), 12,
      ts_builtin_sym_end,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1211] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(30), 1,
      sym_comment,
    ACTIONS(155), 12,
      ts_builtin_sym_end,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1232] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(31), 1,
      sym_comment,
    ACTIONS(157), 12,
      ts_builtin_sym_end,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1253] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(32), 1,
      sym_comment,
    ACTIONS(159), 12,
      ts_builtin_sym_end,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1274] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(33), 1,
      sym_comment,
    ACTIONS(161), 12,
      ts_builtin_sym_end,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1295] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(34), 1,
      sym_comment,
    ACTIONS(163), 12,
      ts_builtin_sym_end,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1316] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(35), 1,
      sym_comment,
    ACTIONS(165), 12,
      ts_builtin_sym_end,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1337] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(36), 1,
      sym_comment,
    ACTIONS(167), 12,
      ts_builtin_sym_end,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1358] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(37), 1,
      sym_comment,
    ACTIONS(169), 12,
      ts_builtin_sym_end,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1379] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(38), 1,
      sym_comment,
    ACTIONS(171), 12,
      ts_builtin_sym_end,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1400] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(39), 1,
      sym_comment,
    ACTIONS(173), 12,
      ts_builtin_sym_end,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1421] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(40), 1,
      sym_comment,
    ACTIONS(175), 12,
      ts_builtin_sym_end,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1442] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(41), 1,
      sym_comment,
    ACTIONS(177), 12,
      ts_builtin_sym_end,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1463] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(42), 1,
      sym_comment,
    ACTIONS(179), 12,
      ts_builtin_sym_end,
      anon_sym_measure,
      anon_sym_x,
      anon_sym_y,
      anon_sym_z,
      anon_sym_hadamard,
      anon_sym_phase,
      anon_sym_pi_8,
      anon_sym_cnot,
      anon_sym_cz,
      anon_sym_swap,
      anon_sym_toffoli,
  [1484] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(183), 1,
      anon_sym_SLASH,
    STATE(43), 1,
      sym_comment,
    ACTIONS(181), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1504] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(187), 1,
      anon_sym_SLASH,
    STATE(44), 1,
      sym_comment,
    ACTIONS(185), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1524] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(191), 1,
      anon_sym_SLASH,
    ACTIONS(193), 1,
      anon_sym_CARET,
    STATE(45), 1,
      sym_comment,
    ACTIONS(189), 7,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1546] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(193), 1,
      anon_sym_CARET,
    ACTIONS(197), 1,
      anon_sym_STAR,
    ACTIONS(199), 1,
      anon_sym_SLASH,
    STATE(46), 1,
      sym_comment,
    ACTIONS(195), 6,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1570] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(203), 1,
      anon_sym_SLASH,
    STATE(47), 1,
      sym_comment,
    ACTIONS(201), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1590] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(193), 1,
      anon_sym_CARET,
    ACTIONS(197), 1,
      anon_sym_STAR,
    ACTIONS(199), 1,
      anon_sym_SLASH,
    STATE(48), 1,
      sym_comment,
    ACTIONS(205), 6,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1614] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(193), 1,
      anon_sym_CARET,
    ACTIONS(209), 1,
      anon_sym_SLASH,
    STATE(49), 1,
      sym_comment,
    ACTIONS(207), 7,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1636] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(213), 1,
      anon_sym_SLASH,
    STATE(50), 1,
      sym_comment,
    ACTIONS(211), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1656] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(217), 1,
      anon_sym_SLASH,
    STATE(51), 1,
      sym_comment,
    ACTIONS(215), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1676] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(221), 1,
      anon_sym_SLASH,
    STATE(52), 1,
      sym_comment,
    ACTIONS(219), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1696] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(225), 1,
      anon_sym_SLASH,
    STATE(53), 1,
      sym_comment,
    ACTIONS(223), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1716] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(229), 1,
      anon_sym_SLASH,
    STATE(54), 1,
      sym_comment,
    ACTIONS(227), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1736] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(233), 1,
      anon_sym_SLASH,
    STATE(55), 1,
      sym_comment,
    ACTIONS(231), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1756] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(237), 1,
      anon_sym_SLASH,
    STATE(56), 1,
      sym_comment,
    ACTIONS(235), 8,
      anon_sym_COMMA,
      anon_sym_PIPE0_GT,
      anon_sym_PIPE1_GT,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [1776] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(193), 1,
      anon_sym_CARET,
    ACTIONS(197), 1,
      anon_sym_STAR,
    ACTIONS(199), 1,
      anon_sym_SLASH,
    ACTIONS(239), 1,
      anon_sym_PIPE0_GT,
    ACTIONS(241), 1,
      anon_sym_PIPE1_GT,
    ACTIONS(243), 1,
      anon_sym_PLUS,
    ACTIONS(245), 1,
      anon_sym_DASH,
    STATE(57), 1,
      sym_comment,
  [1804] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(193), 1,
      anon_sym_CARET,
    ACTIONS(197), 1,
      anon_sym_STAR,
    ACTIONS(199), 1,
      anon_sym_SLASH,
    ACTIONS(241), 1,
      anon_sym_PIPE1_GT,
    ACTIONS(243), 1,
      anon_sym_PLUS,
    ACTIONS(245), 1,
      anon_sym_DASH,
    STATE(58), 1,
      sym_comment,
  [1829] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(193), 1,
      anon_sym_CARET,
    ACTIONS(197), 1,
      anon_sym_STAR,
    ACTIONS(199), 1,
      anon_sym_SLASH,
    ACTIONS(243), 1,
      anon_sym_PLUS,
    ACTIONS(245), 1,
      anon_sym_DASH,
    ACTIONS(247), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      sym_comment,
  [1854] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(193), 1,
      anon_sym_CARET,
    ACTIONS(197), 1,
      anon_sym_STAR,
    ACTIONS(199), 1,
      anon_sym_SLASH,
    ACTIONS(239), 1,
      anon_sym_PIPE0_GT,
    ACTIONS(243), 1,
      anon_sym_PLUS,
    ACTIONS(245), 1,
      anon_sym_DASH,
    STATE(60), 1,
      sym_comment,
  [1879] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(193), 1,
      anon_sym_CARET,
    ACTIONS(197), 1,
      anon_sym_STAR,
    ACTIONS(199), 1,
      anon_sym_SLASH,
    ACTIONS(243), 1,
      anon_sym_PLUS,
    ACTIONS(245), 1,
      anon_sym_DASH,
    ACTIONS(249), 1,
      anon_sym_RPAREN,
    STATE(61), 1,
      sym_comment,
  [1904] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(193), 1,
      anon_sym_CARET,
    ACTIONS(197), 1,
      anon_sym_STAR,
    ACTIONS(199), 1,
      anon_sym_SLASH,
    ACTIONS(243), 1,
      anon_sym_PLUS,
    ACTIONS(245), 1,
      anon_sym_DASH,
    ACTIONS(251), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      sym_comment,
  [1929] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(193), 1,
      anon_sym_CARET,
    ACTIONS(197), 1,
      anon_sym_STAR,
    ACTIONS(199), 1,
      anon_sym_SLASH,
    ACTIONS(243), 1,
      anon_sym_PLUS,
    ACTIONS(245), 1,
      anon_sym_DASH,
    ACTIONS(253), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      sym_comment,
  [1954] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(193), 1,
      anon_sym_CARET,
    ACTIONS(197), 1,
      anon_sym_STAR,
    ACTIONS(199), 1,
      anon_sym_SLASH,
    ACTIONS(243), 1,
      anon_sym_PLUS,
    ACTIONS(245), 1,
      anon_sym_DASH,
    ACTIONS(255), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      sym_comment,
  [1979] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(193), 1,
      anon_sym_CARET,
    ACTIONS(197), 1,
      anon_sym_STAR,
    ACTIONS(199), 1,
      anon_sym_SLASH,
    ACTIONS(243), 1,
      anon_sym_PLUS,
    ACTIONS(245), 1,
      anon_sym_DASH,
    ACTIONS(257), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      sym_comment,
  [2004] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(259), 1,
      sym_uint,
    ACTIONS(261), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      sym_comment,
  [2017] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      sym_comment,
  [2027] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      sym_comment,
  [2037] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(267), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      sym_comment,
  [2047] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(269), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      sym_comment,
  [2057] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      sym_comment,
  [2067] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(273), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      sym_comment,
  [2077] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      sym_comment,
  [2087] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    STATE(74), 1,
      sym_comment,
  [2097] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(279), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      sym_comment,
  [2107] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(281), 1,
      sym_var_name,
    STATE(76), 1,
      sym_comment,
  [2117] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(283), 1,
      sym_var_name,
    STATE(77), 1,
      sym_comment,
  [2127] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(285), 1,
      sym_var_name,
    STATE(78), 1,
      sym_comment,
  [2137] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(287), 1,
      sym_var_name,
    STATE(79), 1,
      sym_comment,
  [2147] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(289), 1,
      sym_var_name,
    STATE(80), 1,
      sym_comment,
  [2157] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(291), 1,
      sym_var_name,
    STATE(81), 1,
      sym_comment,
  [2167] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(293), 1,
      sym_var_name,
    STATE(82), 1,
      sym_comment,
  [2177] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(295), 1,
      sym_var_name,
    STATE(83), 1,
      sym_comment,
  [2187] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(297), 1,
      sym_var_name,
    STATE(84), 1,
      sym_comment,
  [2197] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(299), 1,
      anon_sym_LPAREN,
    STATE(85), 1,
      sym_comment,
  [2207] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(301), 1,
      anon_sym_LPAREN,
    STATE(86), 1,
      sym_comment,
  [2217] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      sym_comment,
  [2227] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(305), 1,
      anon_sym_LPAREN,
    STATE(88), 1,
      sym_comment,
  [2237] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(307), 1,
      anon_sym_LPAREN,
    STATE(89), 1,
      sym_comment,
  [2247] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(309), 1,
      anon_sym_LPAREN,
    STATE(90), 1,
      sym_comment,
  [2257] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(311), 1,
      anon_sym_LPAREN,
    STATE(91), 1,
      sym_comment,
  [2267] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(313), 1,
      anon_sym_LPAREN,
    STATE(92), 1,
      sym_comment,
  [2277] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(315), 1,
      anon_sym_LPAREN,
    STATE(93), 1,
      sym_comment,
  [2287] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(317), 1,
      anon_sym_LPAREN,
    STATE(94), 1,
      sym_comment,
  [2297] = 3,
    ACTIONS(319), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(321), 1,
      aux_sym_comment_token1,
    STATE(95), 1,
      sym_comment,
  [2307] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(323), 1,
      sym_var_name,
    STATE(96), 1,
      sym_comment,
  [2317] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(325), 1,
      sym_var_name,
    STATE(97), 1,
      sym_comment,
  [2327] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(327), 1,
      sym_var_name,
    STATE(98), 1,
      sym_comment,
  [2337] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(329), 1,
      sym_var_name,
    STATE(99), 1,
      sym_comment,
  [2347] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(331), 1,
      anon_sym_EQ,
    STATE(100), 1,
      sym_comment,
  [2357] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(333), 1,
      anon_sym_RPAREN,
    STATE(101), 1,
      sym_comment,
  [2367] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(335), 1,
      anon_sym_RPAREN,
    STATE(102), 1,
      sym_comment,
  [2377] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(337), 1,
      anon_sym_COMMA,
    STATE(103), 1,
      sym_comment,
  [2387] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(339), 1,
      ts_builtin_sym_end,
    STATE(104), 1,
      sym_comment,
  [2397] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(341), 1,
      anon_sym_LPAREN,
    STATE(105), 1,
      sym_comment,
  [2407] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(343), 1,
      anon_sym_RPAREN,
    STATE(106), 1,
      sym_comment,
  [2417] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(345), 1,
      sym_var_name,
    STATE(107), 1,
      sym_comment,
  [2427] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(347), 1,
      sym_var_name,
    STATE(108), 1,
      sym_comment,
  [2437] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(349), 1,
      anon_sym_RPAREN,
    STATE(109), 1,
      sym_comment,
  [2447] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(351), 1,
      anon_sym_RPAREN,
    STATE(110), 1,
      sym_comment,
  [2457] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(353), 1,
      anon_sym_LPAREN,
    STATE(111), 1,
      sym_comment,
  [2467] = 1,
    ACTIONS(355), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 71,
  [SMALL_STATE(4)] = 137,
  [SMALL_STATE(5)] = 199,
  [SMALL_STATE(6)] = 259,
  [SMALL_STATE(7)] = 316,
  [SMALL_STATE(8)] = 373,
  [SMALL_STATE(9)] = 424,
  [SMALL_STATE(10)] = 475,
  [SMALL_STATE(11)] = 526,
  [SMALL_STATE(12)] = 577,
  [SMALL_STATE(13)] = 628,
  [SMALL_STATE(14)] = 679,
  [SMALL_STATE(15)] = 730,
  [SMALL_STATE(16)] = 781,
  [SMALL_STATE(17)] = 832,
  [SMALL_STATE(18)] = 883,
  [SMALL_STATE(19)] = 934,
  [SMALL_STATE(20)] = 964,
  [SMALL_STATE(21)] = 989,
  [SMALL_STATE(22)] = 1014,
  [SMALL_STATE(23)] = 1039,
  [SMALL_STATE(24)] = 1064,
  [SMALL_STATE(25)] = 1091,
  [SMALL_STATE(26)] = 1118,
  [SMALL_STATE(27)] = 1142,
  [SMALL_STATE(28)] = 1166,
  [SMALL_STATE(29)] = 1190,
  [SMALL_STATE(30)] = 1211,
  [SMALL_STATE(31)] = 1232,
  [SMALL_STATE(32)] = 1253,
  [SMALL_STATE(33)] = 1274,
  [SMALL_STATE(34)] = 1295,
  [SMALL_STATE(35)] = 1316,
  [SMALL_STATE(36)] = 1337,
  [SMALL_STATE(37)] = 1358,
  [SMALL_STATE(38)] = 1379,
  [SMALL_STATE(39)] = 1400,
  [SMALL_STATE(40)] = 1421,
  [SMALL_STATE(41)] = 1442,
  [SMALL_STATE(42)] = 1463,
  [SMALL_STATE(43)] = 1484,
  [SMALL_STATE(44)] = 1504,
  [SMALL_STATE(45)] = 1524,
  [SMALL_STATE(46)] = 1546,
  [SMALL_STATE(47)] = 1570,
  [SMALL_STATE(48)] = 1590,
  [SMALL_STATE(49)] = 1614,
  [SMALL_STATE(50)] = 1636,
  [SMALL_STATE(51)] = 1656,
  [SMALL_STATE(52)] = 1676,
  [SMALL_STATE(53)] = 1696,
  [SMALL_STATE(54)] = 1716,
  [SMALL_STATE(55)] = 1736,
  [SMALL_STATE(56)] = 1756,
  [SMALL_STATE(57)] = 1776,
  [SMALL_STATE(58)] = 1804,
  [SMALL_STATE(59)] = 1829,
  [SMALL_STATE(60)] = 1854,
  [SMALL_STATE(61)] = 1879,
  [SMALL_STATE(62)] = 1904,
  [SMALL_STATE(63)] = 1929,
  [SMALL_STATE(64)] = 1954,
  [SMALL_STATE(65)] = 1979,
  [SMALL_STATE(66)] = 2004,
  [SMALL_STATE(67)] = 2017,
  [SMALL_STATE(68)] = 2027,
  [SMALL_STATE(69)] = 2037,
  [SMALL_STATE(70)] = 2047,
  [SMALL_STATE(71)] = 2057,
  [SMALL_STATE(72)] = 2067,
  [SMALL_STATE(73)] = 2077,
  [SMALL_STATE(74)] = 2087,
  [SMALL_STATE(75)] = 2097,
  [SMALL_STATE(76)] = 2107,
  [SMALL_STATE(77)] = 2117,
  [SMALL_STATE(78)] = 2127,
  [SMALL_STATE(79)] = 2137,
  [SMALL_STATE(80)] = 2147,
  [SMALL_STATE(81)] = 2157,
  [SMALL_STATE(82)] = 2167,
  [SMALL_STATE(83)] = 2177,
  [SMALL_STATE(84)] = 2187,
  [SMALL_STATE(85)] = 2197,
  [SMALL_STATE(86)] = 2207,
  [SMALL_STATE(87)] = 2217,
  [SMALL_STATE(88)] = 2227,
  [SMALL_STATE(89)] = 2237,
  [SMALL_STATE(90)] = 2247,
  [SMALL_STATE(91)] = 2257,
  [SMALL_STATE(92)] = 2267,
  [SMALL_STATE(93)] = 2277,
  [SMALL_STATE(94)] = 2287,
  [SMALL_STATE(95)] = 2297,
  [SMALL_STATE(96)] = 2307,
  [SMALL_STATE(97)] = 2317,
  [SMALL_STATE(98)] = 2327,
  [SMALL_STATE(99)] = 2337,
  [SMALL_STATE(100)] = 2347,
  [SMALL_STATE(101)] = 2357,
  [SMALL_STATE(102)] = 2367,
  [SMALL_STATE(103)] = 2377,
  [SMALL_STATE(104)] = 2387,
  [SMALL_STATE(105)] = 2397,
  [SMALL_STATE(106)] = 2407,
  [SMALL_STATE(107)] = 2417,
  [SMALL_STATE(108)] = 2427,
  [SMALL_STATE(109)] = 2437,
  [SMALL_STATE(110)] = 2447,
  [SMALL_STATE(111)] = 2457,
  [SMALL_STATE(112)] = 2467,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(105),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(85),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(86),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(111),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(88),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(89),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(90),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(91),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(92),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(93),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(94),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qubit_zero, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qubit_zero, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qubit_zero, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qubit_zero, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qubit_one, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qubit_one, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qubit_one, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qubit_one, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_expr, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_expr, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_expr, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_expr, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pauli_z, 4, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_toffoli, 8, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_measure, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_measure, 4, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pauli_x, 4, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pauli_y, 4, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__qc_fn, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hadamard, 4, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_phase, 4, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pi_by_8, 4, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_controlled_not, 6, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_controlled_z, 6, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_swap, 6, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__var_fn, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__var_fn, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr, 1, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 3, 0, 2),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 3, 0, 2),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub, 3, 0, 2),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exp, 3, 0, 2),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exp, 3, 0, 2),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add, 3, 0, 2),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul, 3, 0, 2),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mul, 3, 0, 2),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__constant, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__constant, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 3, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr, 3, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root, 5, 0, 3),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root, 5, 0, 3),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binary_expr, 1, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__binary_expr, 1, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sin, 3, 0, 1),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sin, 3, 0, 1),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cos, 3, 0, 1),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cos, 3, 0, 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tan, 3, 0, 1),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tan, 3, 0, 1),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [319] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [321] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [339] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_qc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "qc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
