on:
  push:
    tags: ["*"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: tree-sitter/setup-action@v2
        with:
          install-lib: false
      - run: tree-sitter generate
        working-directory: tree-sitter-qc
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --skip validation
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
